name: "Build & Test"

on:
  push:
    paths:
      - "include/**"
      - "src/**"
      - "lib/**"
      - "test/**"
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: |
          make build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Run tests
        run: |
          make test
